
INSERT INTO study_program_types (description) VALUES
    ('Bachillerato'),
    ('Bachillerato Técnico'),
    ('Técnico'),
    ('Licenciatura'),
    ('Ingeniería'),
    ('Doctorado'),
    ('Especialidad'),
    ('Maestría');

INSERT INTO study_programs (name, is_stem, type, years_to_complete) VALUES
    ('Bachillerato General', false, 1, 3),
    ('Bachillerato en Computación', true, 2, 3),
    ('Técnico Automotriz', false, 3, 2),
    ('Licenciatura en Administración de Empresas', false, 4, 4),
    ('Licenciatura en Psicología', false, 4, 4),
    ('Ingeniería Industrial', true, 5, 5),
    ('Ingeniería Mecánica', true, 5, 5),
    ('Medicina General', true, 6, 6),
    ('Especialidad en Medicina Interna', false, 7, 3),
    ('Maestría en Educación', false, 8, 2);

INSERT INTO departments (name) VALUES 
    ('Ahuachapán'),
    ('Santa Ana'),
    ('Sonsonate'),
    ('Chalatenango'),
    ('La Libertad'),
    ('San Salvador'),
    ('Cuscatlán'),
    ('La Paz'),
    ('Cabañas'),
    ('San Vicente'),
    ('Usulután'),
    ('San Miguel'),
    ('Morazán'),
    ('La Unión');

INSERT INTO municipalities (name, department_id) VALUES 
    -- Municipios de Ahuachapán (ID: 1)
        ('Ahuachapán', 1),
        ('Apaneca', 1),
        ('Atiquizaya', 1),
        ('Concepción de Ataco', 1),
        ('El Refugio', 1),
        ('Guaymango', 1),
        ('Jujutla', 1),
        ('San Francisco Menéndez', 1),
        ('San Lorenzo', 1),
        ('San Pedro Puxtla', 1),
        ('Tacuba', 1),
        ('Turín', 1),

    -- Municipios de Santa Ana (ID: 2)
        ('Santa Ana', 2),
        ('Candelaria de la Frontera', 2),
        ('Chalchuapa', 2),
        ('Coatepeque', 2),
        ('El Congo', 2),
        ('El Porvenir', 2),
        ('Masahuat', 2),
        ('Metapán', 2),
        ('San Antonio Pajonal', 2),
        ('San Sebastián Salitrillo', 2),
        ('Santa Rosa Guachipilín', 2),
        ('Santiago de la Frontera', 2),
        ('Texistepeque', 2),

    -- Municipios de Sonsonate (ID: 3)
        ('Sonsonate', 3),
        ('Acajutla', 3),
        ('Armenia', 3),
        ('Caluco', 3),
        ('Cuisnahuat', 3),
        ('Izalco', 3),
        ('Juayúa', 3),
        ('Nahuizalco', 3),
        ('Nahulingo', 3),
        ('Salcoatitán', 3),
        ('San Antonio del Monte', 3),
        ('San Julián', 3),
        ('Santa Catarina Masahuat', 3),
        ('Santa Isabel Ishuatán', 3),
        ('Santo Domingo de Guzmán', 3),
        ('Sonzacate', 3),

    -- Municipios de Chalatenango (ID: 4)
        ('Chalatenango', 4),
        ('Agua Caliente', 4),
        ('Arcatao', 4),
        ('Azacualpa', 4),
        ('Cancasque', 4),
        ('Citalá', 4),
        ('Comalapa', 4),
        ('Concepción Quezaltepeque', 4),
        ('Dulce Nombre de María', 4),
        ('El Carrizal', 4),
        ('El Paraíso', 4),
        ('La Laguna', 4),
        ('La Palma', 4),
        ('La Reina', 4),
        ('Las Vueltas', 4),
        ('Nombre de Jesús', 4),
        ('Nueva Concepción', 4),
        ('Nueva Trinidad', 4),
        ('Ojos de Agua', 4),
        ('Potonico', 4),
        ('San Antonio de la Cruz', 4),
        ('San Antonio Los Ranchos', 4),
        ('San Fernando', 4),
        ('San Francisco Lempa', 4),
        ('San Francisco Morazán', 4),
        ('San Ignacio', 4),
        ('San Isidro Labrador', 4),
        ('San José Las Flores', 4),
        ('San Luis del Carmen', 4),
        ('San Miguel de Mercedes', 4),
        ('San Rafael', 4),
        ('Santa Rita', 4),
        ('Tejutla', 4),

    -- Municipios de La Libertad (ID: 5)
        ('Santa Tecla', 5),
        ('Antiguo Cuscatlán', 5),
        ('Chiltiupán', 5),
        ('Ciudad Arce', 5),
        ('Colón', 5),
        ('Comasagua', 5),
        ('Huizúcar', 5),
        ('Jayaque', 5),
        ('Jicalapa', 5),
        ('La Libertad', 5),
        ('Nuevo Cuscatlán', 5),
        ('Quezaltepeque', 5),
        ('Sacacoyo', 5),
        ('San José Villanueva', 5),
        ('San Juan Opico', 5),
        ('San Matías', 5),
        ('San Pablo Tacachico', 5),
        ('Talnique', 5),
        ('Tamanique', 5),
        ('Teotepeque', 5),
        ('Tepecoyo', 5),
        ('Zaragoza', 5),

    -- Municipios de San Salvador (ID: 6)
        ('San Salvador', 6),
        ('Aguilares', 6),
        ('Apopa', 6),
        ('Ayutuxtepeque', 6),
        ('Cuscatancingo', 6),
        ('Ciudad Delgado', 6),
        ('El Paisnal', 6),
        ('Guazapa', 6),
        ('Ilopango', 6),
        ('Mejicanos', 6),
        ('Nejapa', 6),
        ('Panchimalco', 6),
        ('Rosario de Mora', 6),
        ('San Marcos', 6),
        ('San Martín', 6),
        ('Santiago Texacuangos', 6),
        ('Santo Tomás', 6),
        ('Soyapango', 6),
        ('Tonacatepeque', 6),

    -- Municipios de Cuscatlán (ID: 7)
        ('Cojutepeque', 7),
        ('Candelaria', 7),
        ('El Carmen', 7),
        ('El Rosario', 7),
        ('Monte San Juan', 7),
        ('Oratorio de Concepción', 7),
        ('San Bartolomé Perulapía', 7),
        ('San Cristóbal', 7),
        ('San José Guayabal', 7),
        ('San Pedro Perulapán', 7),
        ('San Rafael Cedros', 7),
        ('San Ramón', 7),
        ('Santa Cruz Analquito', 7),
        ('Santa Cruz Michapa', 7),
        ('Suchitoto', 7),
        ('Tenancingo', 7),

    -- Municipios de La Paz (ID: 8)
        ('Zacatecoluca', 8),
        ('Cuyultitán', 8),
        ('El Rosario', 8),
        ('Jerusalén', 8),
        ('Mercedes La Ceiba', 8),
        ('Olocuilta', 8),
        ('Paraíso de Osorio', 8),
        ('San Antonio Masahuat', 8),
        ('San Emigdio', 8),
        ('San Francisco Chinameca', 8),
        ('San Juan Nonualco', 8),
        ('San Juan Talpa', 8),
        ('San Juan Tepezontes', 8),
        ('San Luis La Herradura', 8),
        ('San Luis Talpa', 8),
        ('San Miguel Tepezontes', 8),
        ('San Pedro Masahuat', 8),
        ('San Pedro Nonualco', 8),
        ('San Rafael Obrajuelo', 8),
        ('Santa María Ostuma', 8),
        ('Santiago Nonualco', 8),
        ('Tapalhuaca', 8),

    -- Municipios de Cabañas (ID: 9)
        ('Sensuntepeque', 9),
        ('Cinquera', 9),
        ('Dolores', 9),
        ('Guacotecti', 9),
        ('Ilobasco', 9),
        ('Jutiapa', 9),
        ('San Isidro', 9),
        ('Tejutepeque', 9),
        ('Victoria', 9),

    -- Municipios de San Vicente (ID: 10)
        ('San Vicente', 10),
        ('Apastepeque', 10),
        ('Guadalupe', 10),
        ('San Cayetano Istepeque', 10),
        ('San Esteban Catarina', 10),
        ('San Ildefonso', 10),
        ('San Lorenzo', 10),
        ('San Sebastián', 10),
        ('Santa Clara', 10),
        ('Santo Domingo', 10),
        ('Tecoluca', 10),
        ('Tepetitán', 10),
        ('Verapaz', 10),

    -- Municipios de Usulután (ID: 11)
        ('Usulután', 11),
        ('Alegría', 11),
        ('Berlín', 11),
        ('California', 11),
        ('Concepción Batres', 11),
        ('El Triunfo', 11),
        ('Ereguayquín', 11),
        ('Estanzuelas', 11),
        ('Jiquilisco', 11),
        ('Jucuapa', 11),
        ('Jucuarán', 11),
        ('Mercedes Umaña', 11),
        ('Nueva Granada', 11),
        ('Ozatlán', 11),
        ('Puerto El Triunfo', 11),
        ('San Agustín', 11),
        ('San Buenaventura', 11),
        ('San Dionisio', 11),
        ('San Francisco Javier', 11),
        ('Santa Elena', 11),
        ('Santa María', 11),
        ('Santiago de María', 11),
        ('Tecapán', 11),

    -- Municipios de San Miguel (ID: 12)
        ('San Miguel', 12),
        ('Carolina', 12),
        ('Chapeltique', 12),
        ('Chinameca', 12),
        ('Chirilagua', 12),
        ('Ciudad Barrios', 12),
        ('Comacarán', 12),
        ('El Tránsito', 12),
        ('Lolotique', 12),
        ('Moncagua', 12),
        ('Nueva Guadalupe', 12),
        ('Nuevo Edén de San Juan', 12),
        ('Quelepa', 12),
        ('San Antonio del Mosco', 12),
        ('San Gerardo', 12),
        ('San Jorge', 12),
        ('San Luis de la Reina', 12),
        ('San Rafael Oriente', 12),
        ('Sesori', 12),
        ('Uluazapa', 12),

    -- Municipios de Morazán (ID: 13)
        ('San Francisco Gotera', 13),
        ('Arambala', 13),
        ('Cacaopera', 13),
        ('Chilanga', 13),
        ('Corinto', 13),
        ('Delicias de Concepción', 13),
        ('El Divisadero', 13),
        ('El Rosario', 13),
        ('Gualococti', 13),
        ('Guatajiagua', 13),
        ('Joateca', 13),
        ('Jocoaitique', 13),
        ('Jocoro', 13),
        ('Lolotiquillo', 13),
        ('Meanguera', 13),
        ('Osicala', 13),
        ('Perquín', 13),
        ('San Carlos', 13),
        ('San Fernando', 13),
        ('San Isidro', 13),
        ('San Simón', 13),
        ('Sensembra', 13),
        ('Sociedad', 13),
        ('Torola', 13),
        ('Yamabal', 13),
        ('Yoloaiquín', 13),

    -- Municipios de La Unión (ID: 14)
    ('La Unión', 14),
    ('Anamorós', 14),
    ('Bolívar', 14),
    ('Concepción de Oriente', 14),
    ('Conchagua', 14),
    ('El Carmen', 14),
    ('El Sauce', 14),
    ('Intipucá', 14),
    ('Lislique', 14),
    ('Meanguera del Golfo', 14),
    ('Nueva Esparta', 14),
    ('Pasaquina', 14),
    ('Polorós', 14),
    ('San Alejo', 14),
    ('San José', 14),
    ('Santa Rosa de Lima', 14),
    ('Yayantique', 14),
    ('Yucuaiquín', 14);
